[catalogue]
172.31.83.227
172.31.83.227
172.31.83.227
172.31.83.227

[mongodb]
mongodb.sriharidevops17.online

[redis]
redis.sriharidevops17.online

[mysql]
mysql.sriharidevops17.online

[rabbitmq]
rabbitmq.sriharidevops17.online






[frontend]
172.31.4.179
172.31.4.179


[cart]
172.31.83.227
172.31.83.227

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
course=ansible
duration=10hrs
trainer=sivakumar
#name=from inventory

